export { default as HomePage } from './HomePage'
export { default as ProductsPage } from './ProductsPage'
export { default as ProductDetailsPage } from './ProductDetailsPage'
export { default as CartPage } from './CartPage'
export { default as CheckoutPage } from './CheckoutPage'